# -*- coding: utf-8 -*-
"""fraud_detection_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgY0cEghiu9V2yvzEc0kf_pdtrupzVQP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score
)
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import IsolationForest

"""# Detecção de Fraude em Transações de Varejo

## Objetivo

Desenvolver um pipeline completo de Machine Learning para detectar transações fraudulentas em operações de varejo e e-commerce.

"""

df = pd.read_csv("../retail_fraud_detection_100k.csv")
df.head()

print("Shape:", df.shape)
df.info()

df.describe(include='all')

df.isnull().sum()

"""## Análise Exploratória

Nesta etapa foram analisadas as distribuições das variáveis, correlações e o balanceamento das classes.

"""

plt.figure(figsize=(6,4))
sns.countplot(x='fraud_flag', data=df)
plt.title("Distribuição de Fraudes")
plt.show()

print(df['fraud_flag'].value_counts(normalize=True)*100)

plt.figure(figsize=(8,5))
sns.histplot(df['transaction_amount'], bins=40, kde=True)
plt.title("Distribuição dos Valores")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(
    df.select_dtypes(include=['int64','float64']).corr(),
    cmap='coolwarm'
)
plt.show()

"""Foi observada forte correlação entre fraude e variáveis comportamentais como velocity_flag, unusual_location_flag e high_risk_device_flag.

"""

columns_to_drop = [
    'transaction_id',
    'customer_id',
    'transaction_timestamp'
]

# Verifica se as colunas existem antes de tentar removê-las
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]

if existing_columns_to_drop:
    df = df.drop(existing_columns_to_drop, axis=1)
    print(f"Colunas {existing_columns_to_drop} removidas com sucesso.")
else:
    print("As colunas especificadas já foram removidas ou não existem no DataFrame.")

X = df.drop("fraud_flag", axis=1)
y = df["fraud_flag"]

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""## Modelagem

Foram treinados três modelos supervisionados e um método de detecção de anomalias.

"""

## Modelagem

Foram treinados três modelos supervisionados e um método de detecção de anomalias.

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)
rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)
pred_gb = gb.predict(X_test)
# Probabilidades para cálculo do ROC-AUC

prob_lr = lr.predict_proba(X_test)[:, 1]

prob_rf = rf.predict_proba(X_test)[:, 1]

prob_gb = gb.predict_proba(X_test)[:, 1]

def avaliar(nome, y_true, pred, prob=None):

    print("="*40)
    print("Modelo:", nome)
    print("Accuracy:", accuracy_score(y_true, pred))
    print("Precision:", precision_score(y_true, pred))
    print("Recall:", recall_score(y_true, pred))
    print("F1:", f1_score(y_true, pred))

    if prob is not None:
        print("ROC-AUC:", roc_auc_score(y_true, prob))

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, pred))

avaliar("Logistic Regression", y_test, pred_lr, prob_lr)

avaliar("Random Forest", y_test, pred_rf, prob_rf)

avaliar("Gradient Boosting", y_test, pred_gb, prob_gb)

iso = IsolationForest(
    contamination=0.05,
    random_state=42
)

iso.fit(X_train)
pred_iso = iso.predict(X_test)
pred_iso = np.where(pred_iso == -1, 1, 0)

avaliar("Isolation Forest", y_test, pred_iso)

lr = LogisticRegression(random_state=42, solver='liblinear') # Adicionando solver para evitar warning
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)

resultados = pd.DataFrame({

    "Modelo":[
        "Logistic Regression",
        "Random Forest",
        "Gradient Boosting",
        "Isolation Forest"
    ],

    "Accuracy":[
        accuracy_score(y_test,pred_lr),
        accuracy_score(y_test,pred_rf),
        accuracy_score(y_test,pred_gb),
        accuracy_score(y_test,pred_iso)
    ],

    "F1":[
        f1_score(y_test,pred_lr),
        f1_score(y_test,pred_rf),
        f1_score(y_test,pred_gb),
        f1_score(y_test,pred_iso)
    ],

    "ROC-AUC":[
        roc_auc_score(y_test,prob_lr),
        roc_auc_score(y_test,prob_rf),
        roc_auc_score(y_test,prob_gb),
        np.nan
    ]

})

resultados

"""## Conclusão

Os resultados demonstraram que a Logistic Regression e o Random Forest apresentaram desempenho praticamente perfeito nas métricas avaliadas (Accuracy, Precision, Recall, F1-score e ROC-AUC). O Gradient Boosting também apresentou excelente desempenho, embora ligeiramente inferior. Em contrapartida, o Isolation Forest obteve resultados significativamente menores, evidenciando que, para este conjunto de dados, os modelos supervisionados são mais eficazes na detecção de fraudes.

"""